// GENERATED by scripts/generate_stellaris_space_industry.py. Do not hand-edit.
ServerEvents.recipes(event => {
    const I = id => `kubejs:${id}`
    const press = (out, input) => event.recipes.create.pressing(I(out), input.startsWith('#') ? Ingredient.of(input) : input).id(`infinite_domain:space/pressing/${out}`)
    const cut = (out, count, input) => event.recipes.create.cutting(Item.of(I(out), count), input).id(`infinite_domain:space/cutting/${out}`)
    const mix = (out, inputs, heat) => {
        const recipe = event.recipes.create.mixing(out, inputs).id(`infinite_domain:space/mixing/${String(out).replace(/[^a-z0-9_]+/gi, '_')}`)
        if (heat === 'heated') recipe.heated()
        if (heat === 'superheated') recipe.superheated()
        return recipe
    }
    const compact = (out, inputs) => event.recipes.create.compacting(out, inputs).id(`infinite_domain:space/compacting/${String(out).replace(/[^a-z0-9_]+/gi, '_')}`)
    const deploy = (out, base, applied) => event.recipes.create.deploying(I(out), [base, applied]).id(`infinite_domain:space/deploying/${out}`)
    const seq = (out, input, transitional, loops, applied) => event.custom({
        type: 'create:sequenced_assembly', ingredient: {item: input}, loops: loops,
        results: [{id: I(out), count: 1}], transitional_item: {id: I(transitional)},
        sequence: applied.map(id => ({
                type: 'create:deploying',
                ingredients: [{item: I(transitional)}, id.startsWith('#') ? {tag: id.slice(1)} : {item: id}],
                results: [{id: I(transitional), count: 1}]
            })).concat([{
                type: 'create:pressing',
                ingredients: [{item: I(transitional)}],
                results: [{id: I(transitional), count: 1}]
            }])
    }).id(`infinite_domain:space/sequenced/${out}`)

    // Planetary ore beneficiation: crushing -> separation -> chemical or thermal reduction.
    // create:splashing is water-only fan washing (no fluid ingredient exists), so it is
    // kept only for genuinely aqueous steps; airless lunar separation uses milling instead.
    event.recipes.create.crushing([Item.of(I('crushed_ilmenite'), 2), CreateItem.of('stellaris:moon_stone_dust', 0.35)], I('moon_ilmenite_ore')).id('infinite_domain:space/moon/crush_ilmenite')
    event.recipes.create.milling([Item.of(I('titanium_concentrate')), CreateItem.of(I('lunar_oxygen_feed'), 0.75)], I('crushed_ilmenite')).id('infinite_domain:space/moon/mill_ilmenite')
    event.recipes.create.crushing([Item.of(I('rare_earth_concentrate'), 2), CreateItem.of('stellaris:moon_stone_dust', 0.5)], I('moon_kreep_ore')).id('infinite_domain:space/moon/crush_kreep')
    event.recipes.create.crushing([Item.of(I('helium3_adsorbate')), Item.of('stellaris:moon_stone_dust', 2)], I('moon_helium_regolith')).id('infinite_domain:space/moon/heat_regolith')
    event.recipes.create.crushing([Item.of(I('lunar_ceramic'), 2), Item.of('tfmg:aluminum_nugget', 3)], I('moon_anorthosite_ore')).id('infinite_domain:space/moon/crush_anorthosite')
    event.recipes.create.crushing(Item.of(I('crushed_hematite'), 2), I('mars_hematite_ore')).id('infinite_domain:space/mars/crush_hematite')
    event.recipes.create.crushing(Item.of(I('sulfate_salts'), 2), I('mars_sulfate_ore')).id('infinite_domain:space/mars/crush_sulfate')
    event.recipes.create.crushing(Item.of(I('perchlorate_salts'), 2), I('mars_perchlorate_ore')).id('infinite_domain:space/mars/crush_perchlorate')
    event.recipes.create.crushing(Item.of(I('nickel_cobalt_concentrate'), 2), I('mars_nickel_cobalt_ore')).id('infinite_domain:space/mars/crush_nickel_cobalt')
    event.recipes.create.crushing(Item.of(I('brine_salts'), 2), I('mars_brine_ore')).id('infinite_domain:space/mars/crush_brine')
    event.recipes.create.splashing([Item.of('minecraft:iron_nugget', 8), CreateItem.of(I('sulfate_salts'), 0.25)], I('crushed_hematite')).id('infinite_domain:space/mars/wash_hematite')
    event.recipes.create.crushing(Item.of(I('sulfur_concentrate'), 2), I('venus_sulfur_ore')).id('infinite_domain:space/venus/crush_sulfur')
    event.recipes.create.crushing(Item.of(I('vanadium_concentrate'), 2), I('venus_vanadium_ore')).id('infinite_domain:space/venus/crush_vanadium')
    event.recipes.create.crushing(Item.of(I('tungsten_concentrate'), 2), I('venus_tungsten_ore')).id('infinite_domain:space/venus/crush_tungsten')
    event.recipes.create.crushing(Item.of(I('refractory_concentrate'), 2), I('venus_refractory_ore')).id('infinite_domain:space/venus/crush_refractory')
    compact(Item.of(I('lunar_ceramic'), 2), [I('moon_silicate_ore'), 'minecraft:clay_ball']).heated()
    mix(Item.of(I('martian_catalyst'), 2), [I('nickel_cobalt_concentrate'), I('sulfate_salts'), 'create:powdered_obsidian'], 'heated')
    compact(Item.of(I('martian_geopolymer'), 2), [I('mars_silicate_ore'), I('sulfate_salts'), Fluid.of('minecraft:water', 250)]).heated()
    mix([Fluid.of('minecraft:water', 250), Item.of(I('sulfate_salts'))], [Item.of(I('brine_salts'), 2)], 'heated').id('infinite_domain:space/mars/brine_water_recovery')
    mix(I('venus_atmospheric_sorbent'), [I('sulfur_concentrate'), I('refractory_concentrate'), Fluid.of('tfmg:carbon_dioxide', 1000)], 'superheated').id('infinite_domain:space/venus/atmospheric_capture')
    mix(I('venus_superalloy'), [I('vanadium_concentrate'), I('tungsten_concentrate'), 'stellaris:heavy_metal_ingot', 'stellaris:desh_ingot', I('rare_earth_concentrate')], 'superheated')

    // Structural and thermal families.
    press('aerospace_aluminum_sheet', '#c:ingots/aluminum')
    compact(I('desh_titanium_laminate'), [I('titanium_concentrate'), 'stellaris:desh_ingot', 'immersiveengineering:plate_nickel']).heated()
    cut('structural_truss', 2, I('aerospace_aluminum_sheet'))
    deploy('reinforced_frame', I('structural_truss'), 'immersiveengineering:component_steel')
    compact(I('pressure_bulkhead'), [I('reinforced_frame'), I('aerospace_aluminum_sheet'), 'tfmg:rubber_sheet'])
    compact(I('structural_composite'), ['oritech:carbon_fibre_strands', 'tfmg:plastic_sheet', 'create:sturdy_sheet']).heated()
    compact(I('aerospace_composite'), [I('structural_composite'), I('desh_titanium_laminate'), 'oritech:reinforced_carbon_sheet']).heated()
    mix(Item.of(I('ceramic_fiber'), 2), [I('lunar_ceramic'), 'createnuclear:graphite_rod', 'minecraft:string'], 'heated')
    compact(Item.of(I('thermal_shield_tile'), 2), [I('ceramic_fiber'), 'create:powdered_obsidian']).heated()
    compact(I('ablative_panel'), [I('thermal_shield_tile'), 'tfmg:plastic_sheet', 'createnuclear:graphite_rod']).heated()
    compact(I('radiation_laminate'), ['immersiveengineering:plate_lead', 'createnuclear:graphite_rod', I('rare_earth_concentrate')]).heated()
    compact(I('extreme_environment_composite'), [I('aerospace_composite'), I('venus_superalloy'), I('refractory_concentrate'), I('venus_atmospheric_sorbent')]).heated()
    seq('fuselage_section', I('reinforced_frame'), 'incomplete_fuselage_section', 2, [I('aerospace_aluminum_sheet'), I('structural_truss'), I('pressure_bulkhead'), I('aerospace_composite')])
    compact(I('thermal_protection_package'), [Item.of(I('thermal_shield_tile'), 4), Item.of(I('ablative_panel'), 2), I('radiation_laminate')])

    // Pressure hardware hierarchy.
    compact('kubejs:pressure_vessel', ['tfmg:steel_fluid_tank', '#c:plates/steel', 'tfmg:rubber_sheet'])
    deploy('reinforced_pressure_vessel', I('pressure_vessel'), 'tfmg:heavy_plate')
    deploy('aerospace_pressure_vessel', I('reinforced_pressure_vessel'), I('desh_titanium_laminate'))
    deploy('venus_pressure_vessel', I('aerospace_pressure_vessel'), I('extreme_environment_composite'))
    deploy('precision_valve', 'tfmg:steel_fluid_valve', 'powergrid:integrated_circuit')
    deploy('high_pressure_valve', I('precision_valve'), 'tfmg:heavy_plate')
    deploy('cryogenic_valve', I('high_pressure_valve'), I('ceramic_fiber'))
    compact(I('aerospace_pump'), ['tfmg:electric_pump', I('high_pressure_valve'), 'create_new_age:advanced_motor'])
    compact(I('oxygen_manifold'), [Item.of(I('precision_valve'), 2), I('aerospace_pressure_vessel'), 'create:fluid_pipe'])
    compact(I('propellant_manifold'), [Item.of(I('cryogenic_valve'), 2), I('aerospace_pressure_vessel'), 'tfmg:steel_pipe'])
    compact(Item.of(I('empty_gas_cylinder'), 2), [I('aerospace_aluminum_sheet'), I('precision_valve')])
    event.recipes.create.filling(I('oxygen_cylinder'), [I('empty_gas_cylinder'), Fluid.of('stellaris:oxygen', 1000)]).id('infinite_domain:space/filling/oxygen_cylinder')
    event.recipes.create.filling(I('hydrogen_cylinder'), [I('empty_gas_cylinder'), Fluid.of('stellaris:hydrogen', 1000)]).id('infinite_domain:space/filling/hydrogen_cylinder')
    event.recipes.create.filling(I('methane_cylinder'), [I('empty_gas_cylinder'), Fluid.of('stellaris:fuel', 1000)]).id('infinite_domain:space/filling/methane_cylinder')

    // Avionics reuse the established electrical and AE2 industries.
    compact(I('sensor_package'), ['immersiveengineering:component_electronic', 'create:electron_tube', 'powergrid:integrated_circuit'])
    compact(I('guidance_computer'), ['ae2:calculation_processor', I('sensor_package'), 'powergrid:circuit_board'])
    compact(I('navigation_unit'), ['ae2:engineering_processor', I('guidance_computer'), 'minecraft:compass'])
    compact(I('telemetry_array'), ['stellaris:antenna', I('sensor_package'), 'ae2:wireless_receiver'])
    compact(I('power_distribution_unit'), ['create_new_age:generator_coil', 'powergrid:integrated_circuit', 'immersiveengineering:coil_hv'])
    seq('avionics_controller', I('power_distribution_unit'), 'incomplete_avionics_controller', 2, [I('guidance_computer'), I('telemetry_array'), I('sensor_package')])
    deploy('radiation_hardened_controller', I('avionics_controller'), I('radiation_laminate'))
    compact(I('flight_control_computer'), [Item.of(I('radiation_hardened_controller'), 2), I('navigation_unit'), 'ae2:engineering_processor'])
    compact(I('avionics_bay'), [I('flight_control_computer'), I('telemetry_array'), I('power_distribution_unit'), I('reinforced_frame')])

    // Life support and four oxygen economies.
    compact(I('electrolysis_membrane'), ['immersiveengineering:plate_nickel', 'tfmg:plastic_sheet', 'ae2:quartz_glass'])
    compact(I('carbon_scrubber'), ['minecraft:charcoal', 'tfmg:plastic_sheet', I('precision_valve')])
    compact(I('humidity_reclaimer'), [I('aerospace_pump'), I('sensor_package'), 'create:copper_sheet'])
    compact(I('oxygen_regulator'), [I('precision_valve'), I('sensor_package'), 'tfmg:rubber_sheet'])
    compact(I('life_support_controller'), ['powergrid:integrated_circuit', I('sensor_package'), I('oxygen_regulator')])
    seq('closed_loop_life_support', I('life_support_controller'), 'incomplete_life_support_assembly', 2, [I('carbon_scrubber'), I('humidity_reclaimer'), I('oxygen_manifold')])
    compact(I('life_support_module'), [I('closed_loop_life_support'), Item.of(I('oxygen_cylinder'), 2), I('pressure_bulkhead'), I('thermal_protection_package')])
    mix(Fluid.of('stellaris:oxygen', 750), [Fluid.of('minecraft:water', 1000), I('electrolysis_membrane'), 'create_new_age:generator_coil'], 'heated').id('infinite_domain:space/oxygen/terrestrial_electrolysis')
    mix([Fluid.of('stellaris:oxygen', 1000), Item.of(I('titanium_concentrate'))], [Item.of(I('lunar_oxygen_feed'), 2), 'createnuclear:graphite_rod'], 'superheated').id('infinite_domain:space/oxygen/lunar_mineral_reduction')
    mix(Fluid.of('stellaris:oxygen', 1250), [Item.of(I('perchlorate_salts'), 2), I('martian_catalyst'), Fluid.of('tfmg:carbon_dioxide', 1000)], 'heated').id('infinite_domain:space/oxygen/martian_atmospheric_separation')
    mix([Fluid.of('stellaris:oxygen', 900), I('spent_scrubber')], [I('carbon_scrubber'), Fluid.of('minecraft:water', 250), 'minecraft:charcoal'], 'heated').id('infinite_domain:space/oxygen/closed_loop_recovery')
    mix(I('carbon_scrubber'), [I('spent_scrubber'), 'minecraft:charcoal'], 'heated').id('infinite_domain:space/oxygen/scrubber_regeneration')

    // Three propellant paths: petroleum, Mars methalox and advanced hydrogen.
    mix(Fluid.of('stellaris:fuel', 1000), [Fluid.of('petrochem:kerosene', 750), Fluid.of('petrochem:hydrogen', 250), I('sulfur_concentrate')], 'heated').id('infinite_domain:space/fuel/petroleum_route')
    mix(Fluid.of('stellaris:fuel', 1250), [Fluid.of('tfmg:carbon_dioxide', 1000), Fluid.of('stellaris:hydrogen', 1000), I('martian_catalyst')], 'superheated').id('infinite_domain:space/fuel/mars_methalox_route')
    mix(Fluid.of('stellaris:hydrogen', 1000), [Fluid.of('minecraft:water', 1000), I('electrolysis_membrane'), I('rare_earth_concentrate'), I('helium3_adsorbate')], 'superheated').id('infinite_domain:space/fuel/advanced_hydrogen_route')

    // Propulsion is a component tree, not a single expensive grid.
    press('injector_plate', I('desh_titanium_laminate'))
    seq('turbopump', I('aerospace_pump'), 'incomplete_turbopump', 2, ['create_new_age:advanced_motor', I('cryogenic_valve'), I('precision_valve')])
    compact(I('combustion_chamber'), [Item.of(I('desh_titanium_laminate'), 2), I('injector_plate'), 'create_new_age:heat_pipe'])
    compact(I('engine_nozzle'), [I('venus_superalloy'), I('ceramic_fiber'), 'stellaris:heavy_metal_plate'])
    compact(I('gimbal_actuator'), ['create:mechanical_piston', 'create_new_age:reinforced_motor', I('sensor_package')])
    compact(I('ignition_controller'), ['powergrid:integrated_circuit', 'create_new_age:overcharged_golden_sheet', I('sensor_package')])
    compact(I('petroleum_engine_assembly'), [I('turbopump'), I('combustion_chamber'), I('engine_nozzle'), I('gimbal_actuator'), I('ignition_controller'), I('propellant_manifold')])
    compact(I('methalox_engine_assembly'), [I('petroleum_engine_assembly'), I('martian_catalyst'), I('cryogenic_valve'), I('radiation_hardened_controller')])
    compact(I('hydrogen_engine_assembly'), [I('methalox_engine_assembly'), I('rare_earth_concentrate'), I('venus_superalloy'), I('flight_control_computer')])
    compact(I('propellant_tank_section'), [Item.of(I('aerospace_pressure_vessel'), 4), Item.of(I('cryogenic_valve'), 2), I('propellant_manifold'), I('structural_truss')])
    compact(I('service_module'), [I('propellant_tank_section'), I('power_distribution_unit'), I('life_support_controller'), I('aerospace_pump')])
    compact(I('landing_gear_assembly'), [Item.of(I('structural_truss'), 3), Item.of(I('gimbal_actuator'), 2), 'create:sturdy_sheet'])
    compact(I('payload_adapter'), [I('reinforced_frame'), I('sensor_package'), 'create:mechanical_bearing'])

    // Mission sidegrades retain different economic niches.
    compact(I('earth_launch_package'), [I('petroleum_engine_assembly'), I('propellant_tank_section'), I('avionics_bay')])
    compact(I('lunar_cargo_package'), [I('payload_adapter'), Item.of(I('landing_gear_assembly'), 2), I('desh_titanium_laminate'), I('radiation_hardened_controller')])
    compact(I('mars_transfer_package'), [I('methalox_engine_assembly'), I('closed_loop_life_support'), I('martian_catalyst'), I('martian_geopolymer'), I('thermal_protection_package')])
    compact(I('venus_return_package'), [I('hydrogen_engine_assembly'), I('venus_pressure_vessel'), I('extreme_environment_composite'), I('flight_control_computer')])
    compact(I('emergency_return_package'), [I('petroleum_engine_assembly'), I('navigation_unit'), I('oxygen_cylinder'), I('landing_gear_assembly')])
    event.shaped('stellaris:tiny_rocket_upgrade', [' P ', 'MBM', ' P '], {P: I('emergency_return_package'), M: 'stellaris:base_module_tier_1', B: I('payload_adapter')}).id('infinite_domain:space/mission/emergency_return_upgrade')
    event.shaped('stellaris:small_rocket_upgrade', [' P ', 'MBM', ' P '], {P: I('earth_launch_package'), M: 'stellaris:base_module_tier_1', B: I('payload_adapter')}).id('infinite_domain:space/mission/earth_launch_upgrade')
    event.shaped('stellaris:normal_rocket_upgrade', [' P ', 'MBM', ' P '], {P: I('lunar_cargo_package'), M: 'stellaris:base_module_tier_2', B: I('payload_adapter')}).id('infinite_domain:space/mission/lunar_cargo_upgrade')
    event.shaped('stellaris:big_rocket_upgrade', [' P ', 'MBM', ' P '], {P: I('mars_transfer_package'), M: 'stellaris:base_module_tier_2', B: I('service_module')}).id('infinite_domain:space/mission/mars_transfer_upgrade')
    event.shaped('stellaris:big_fuel_tank_upgrade', [' P ', 'MBM', ' P '], {P: I('venus_return_package'), M: 'stellaris:base_module_tier_2', B: I('propellant_tank_section')}).id('infinite_domain:space/mission/venus_return_upgrade')

    // Count-preserving logistics units. Unpacking recovers the exact contents.
    const packages = [
        ['structural_parts_crate', I('fuselage_section'), 4], ['life_support_crate', I('life_support_module'), 4],
        ['avionics_crate', I('avionics_bay'), 4], ['propellant_equipment_crate', I('propellant_manifold'), 8],
        ['lunar_material_pallet', I('desh_titanium_laminate'), 16], ['martian_chemical_pallet', I('martian_catalyst'), 16],
        ['venus_material_pallet', I('venus_superalloy'), 16]
    ]
    packages.forEach(([packed, content, count]) => {
        compact(I(packed), [Item.of(content, count), 'create:cardboard_block'])
        event.shapeless(Item.of(content, count), [I(packed)]).id(`infinite_domain:space/unpacking/${packed}`)
    })

    // Partial recovery only; launch hardware never recycles at 100% yield.
    event.recipes.create.crushing([Item.of('tfmg:steel_nugget', 5), CreateItem.of('create:iron_sheet', 0.5)], I('pressure_vessel')).id('infinite_domain:space/recycling/pressure_vessel')
    event.recipes.create.crushing([Item.of('ae2:silicon', 2), CreateItem.of('immersiveengineering:component_electronic', 0.35)], I('avionics_controller')).id('infinite_domain:space/recycling/avionics_controller')
})
