// Generated by scripts/build_old_world_narrative.py.
// Narrative evidence is non-craftable and structure-bound.
StartupEvents.registry('item', event => {
    event.create('atlas_service_plate')
        .displayName('Atlas Kinetic Service Plate')
        .texture('create:item/precision_mechanism')
        .rarity('uncommon')
        .glow(true)
        .maxStackSize(1)
        .tooltip('§6OWS-009 // Roadside Automated Repair Depot')
        .tooltip('§7Stamped to an Atlas Kinetic service frame recovered in situ')
        .tooltip('§8Quest proof — return this evidence to Charles')

    event.create('atlas_transfer_maintenance_manual')
        .displayName('Automated Transfer Maintenance Manual')
        .texture('minecraft:item/written_book')
        .rarity('uncommon')
        .maxStackSize(1)
        .tooltip('§6Atlas Kinetic Industries // Field Edition 6')
        .tooltip('§7Service lanes, transfer gearing, lockout procedure, and spare-shaft tolerances')
        .tooltip('§8LOR-006 // Early Old World industrial record')
})
