// GENERATED by scripts/generate_stellaris_space_industry.py. Do not hand-edit.
const SPACE_INDUSTRY_ITEMS = [
        ['aerospace_aluminum_sheet', "Aerospace Aluminum Sheet", "Formed, inspected light-alloy skin", 'structure'],
        ['desh_titanium_laminate', "Desh-Titanium Laminate", "Lunar laminate for pressure structures", 'structure'],
        ['structural_truss', "Aerospace Structural Truss", "Load-bearing launch vehicle framing", 'structure'],
        ['reinforced_frame', "Reinforced Aerospace Frame", "Machined frame for major assemblies", 'structure'],
        ['pressure_bulkhead', "Pressure Bulkhead", "Sealed crew-volume divider", 'structure'],
        ['incomplete_fuselage_section', "Incomplete Fuselage Section", "Partially assembled pressure-rated vehicle barrel", 'structure'],
        ['fuselage_section', "Fuselage Section", "Complete pressure-rated vehicle barrel", 'structure'],
        ['landing_gear_assembly', "Landing Gear Assembly", "Shock-isolated planetary landing structure", 'structure'],
        ['payload_adapter', "Payload Adapter", "Standardized cargo and mission interface", 'structure'],
        ['pressure_vessel', "Basic Pressure Vessel", "Terrestrial gas-process vessel", 'pressure'],
        ['reinforced_pressure_vessel', "Reinforced Pressure Vessel", "High-cycle industrial vessel", 'pressure'],
        ['aerospace_pressure_vessel', "Aerospace Pressure Vessel", "Mass-efficient flight vessel", 'pressure'],
        ['venus_pressure_vessel', "Venus-Rated Pressure Vessel", "Extreme-temperature pressure hardware", 'pressure'],
        ['precision_valve', "Precision Valve", "Metered process-fluid control", 'pressure'],
        ['high_pressure_valve', "High-Pressure Valve", "Reinforced gas-service valve", 'pressure'],
        ['cryogenic_valve', "Cryogenic Valve", "Low-temperature propellant valve", 'pressure'],
        ['aerospace_pump', "Aerospace Pump", "Compact flight-qualified turbopump feed", 'pressure'],
        ['oxygen_manifold', "Oxygen Manifold", "Clean-service oxygen distribution", 'pressure'],
        ['propellant_manifold', "Propellant Manifold", "Redundant engine feed distribution", 'pressure'],
        ['empty_gas_cylinder', "Empty Gas Cylinder", "Reusable compressed-gas logistics vessel", 'pressure'],
        ['oxygen_cylinder', "Oxygen Cylinder", "Filled personal and habitat oxygen supply", 'pressure'],
        ['hydrogen_cylinder', "Hydrogen Cylinder", "Filled hydrogen process supply", 'pressure'],
        ['methane_cylinder', "Methane Cylinder", "Filled synthetic propellant supply", 'pressure'],
        ['sensor_package', "Aerospace Sensor Package", "Pressure, temperature and motion instrumentation", 'electronics'],
        ['guidance_computer', "Guidance Computer", "Redundant launch guidance electronics", 'electronics'],
        ['navigation_unit', "Navigation Unit", "Interplanetary position and burn solution unit", 'electronics'],
        ['telemetry_array', "Telemetry Array", "Long-range vehicle health reporting", 'electronics'],
        ['power_distribution_unit', "Power Distribution Unit", "Fault-isolated aerospace power bus", 'electronics'],
        ['incomplete_avionics_controller', "Incomplete Avionics Controller", "Partially integrated flight-control electronics", 'electronics'],
        ['avionics_controller', "Avionics Controller", "Flight-rated control electronics", 'electronics'],
        ['radiation_hardened_controller', "Radiation-Hardened Controller", "Lunar rare-earth hardened control package", 'electronics'],
        ['flight_control_computer', "Flight Control Computer", "Triple-redundant mission controller", 'electronics'],
        ['avionics_bay', "Avionics Bay", "Integrated guidance, telemetry and power section", 'electronics'],
        ['ceramic_fiber', "Ceramic Fiber", "High-temperature woven insulation", 'thermal'],
        ['thermal_shield_tile', "Thermal Shield Tile", "Reusable atmospheric-entry tile", 'thermal'],
        ['ablative_panel', "Ablative Panel", "Sacrificial high-heat protection", 'thermal'],
        ['radiation_laminate', "Radiation Shield Laminate", "Layered nuclear-era shielding", 'thermal'],
        ['structural_composite', "Structural Composite", "Fiber-reinforced vehicle material", 'thermal'],
        ['aerospace_composite', "Aerospace Composite", "Vacuum-rated lightweight composite", 'thermal'],
        ['extreme_environment_composite', "Extreme-Environment Composite", "Venusian refractory composite", 'thermal'],
        ['thermal_protection_package', "Thermal Protection Package", "Complete entry and engine heat system", 'thermal'],
        ['electrolysis_membrane', "Electrolysis Membrane", "Reusable terrestrial water-splitting element", 'life_support'],
        ['carbon_scrubber', "Carbon Scrubber Cartridge", "Replaceable carbon-dioxide sorbent bed", 'life_support'],
        ['spent_scrubber', "Spent Scrubber Cartridge", "Loaded cartridge ready for regeneration", 'life_support'],
        ['humidity_reclaimer', "Humidity Reclaimer", "Condensate recovery and sterilization unit", 'life_support'],
        ['oxygen_regulator', "Oxygen Regulator", "Suit and habitat breathing-gas regulator", 'life_support'],
        ['life_support_controller', "Life-Support Controller", "Atmosphere monitoring and emergency isolation", 'life_support'],
        ['incomplete_life_support_assembly', "Incomplete Life-Support Assembly", "Partially plumbed closed-loop atmosphere plant", 'life_support'],
        ['closed_loop_life_support', "Closed-Loop Life-Support Assembly", "High-efficiency habitat atmosphere plant", 'life_support'],
        ['life_support_module', "Vehicle Life-Support Module", "Crewed-flight atmosphere and thermal package", 'life_support'],
        ['injector_plate', "Engine Injector Plate", "Precision propellant atomization plate", 'propulsion'],
        ['incomplete_turbopump', "Incomplete Rocket Turbopump", "Partially assembled high-speed propellant pump", 'propulsion'],
        ['turbopump', "Rocket Turbopump", "High-speed propellant feed assembly", 'propulsion'],
        ['combustion_chamber', "Combustion Chamber", "Regeneratively cooled engine chamber", 'propulsion'],
        ['engine_nozzle', "Engine Nozzle", "High-expansion refractory exhaust bell", 'propulsion'],
        ['gimbal_actuator', "Gimbal Actuator", "Thrust-vector control actuator", 'propulsion'],
        ['ignition_controller', "Ignition Controller", "Sequenced, redundant engine ignition", 'propulsion'],
        ['petroleum_engine_assembly', "Petroleum Engine Assembly", "Rugged high-thrust terrestrial engine", 'propulsion'],
        ['methalox_engine_assembly', "Methalox Engine Assembly", "Efficient Mars-supported engine", 'propulsion'],
        ['hydrogen_engine_assembly', "Hydrogen Engine Assembly", "High-efficiency cryogenic engine", 'propulsion'],
        ['propellant_tank_section', "Propellant Tank Section", "Insulated dual-propellant vehicle section", 'propulsion'],
        ['service_module', "Vehicle Service Module", "Power, propulsion and life-support services", 'propulsion'],
        ['crushed_ilmenite', "Crushed Lunar Ilmenite", "Oxygen-bearing titanium feed", 'planetary'],
        ['lunar_oxygen_feed', "Reduced Lunar Oxygen Feed", "Prepared mineral oxygen charge", 'planetary'],
        ['titanium_concentrate', "Titanium Concentrate", "Refined lunar titanium feedstock", 'planetary'],
        ['rare_earth_concentrate', "KREEP Rare-Earth Concentrate", "Lunar electronics and catalyst feed", 'planetary'],
        ['helium3_adsorbate', "Helium-3 Regolith Adsorbate", "Concentrated volatile-bearing regolith", 'planetary'],
        ['lunar_ceramic', "Lunar Structural Ceramic", "Locally fired construction ceramic", 'planetary'],
        ['crushed_hematite', "Crushed Martian Hematite", "Iron-rich Martian process feed", 'planetary'],
        ['sulfate_salts', "Martian Sulfate Salts", "Chemical and construction feedstock", 'planetary'],
        ['perchlorate_salts', "Martian Perchlorate Salts", "Hazardous oxidizer-bearing salts", 'planetary'],
        ['nickel_cobalt_concentrate', "Martian Nickel-Cobalt Concentrate", "Catalyst and superalloy feed", 'planetary'],
        ['brine_salts', "Martian Brine Salts", "Hydrated local chemical feed", 'planetary'],
        ['martian_catalyst', "Martian Methanation Catalyst", "Nickel-cobalt catalyst for synthetic fuel", 'planetary'],
        ['martian_geopolymer', "Martian Structural Geopolymer", "Locally cast sulfate-silicate construction material", 'planetary'],
        ['sulfur_concentrate', "Venusian Sulfur Concentrate", "High-purity sulfur process feed", 'planetary'],
        ['vanadium_concentrate', "Vanadium Concentrate", "Extreme-alloy additive", 'planetary'],
        ['tungsten_concentrate', "Tungsten Concentrate", "Refractory metal feedstock", 'planetary'],
        ['refractory_concentrate', "Exotic Refractory Concentrate", "Venusian extreme-material feed", 'planetary'],
        ['venus_atmospheric_sorbent', "Venus Atmospheric Sorbent", "Loaded high-pressure atmospheric capture bed", 'planetary'],
        ['venus_superalloy', "Venusian Superalloy", "Cross-planet high-temperature structural alloy", 'planetary'],
        ['structural_parts_crate', "Structural Parts Crate", "Count-preserving aerospace parts shipment", 'logistics'],
        ['life_support_crate', "Life-Support Supply Crate", "Filters, seals and atmosphere hardware", 'logistics'],
        ['avionics_crate', "Avionics Crate", "Shock-isolated electronics shipment", 'logistics'],
        ['propellant_equipment_crate', "Propellant Equipment Crate", "Valves, pumps and manifold shipment", 'logistics'],
        ['lunar_material_pallet', "Lunar Materials Pallet", "Bulk return shipment of lunar products", 'logistics'],
        ['martian_chemical_pallet', "Martian Chemical Pallet", "Bulk ISRU chemical shipment", 'logistics'],
        ['venus_material_pallet', "Venus Materials Pallet", "Extreme-material interplanetary shipment", 'logistics'],
        ['earth_launch_package', "Earth Launch Package", "High-thrust petroleum mission fit", 'mission'],
        ['lunar_cargo_package', "Lunar Cargo Package", "Cargo-efficient lunar logistics fit", 'mission'],
        ['mars_transfer_package', "Mars Transfer Package", "Methalox-supported interplanetary fit", 'mission'],
        ['venus_return_package', "Venus Return Package", "Extreme-environment return mission fit", 'mission'],
        ['emergency_return_package', "Emergency Return Package", "Rugged low-capacity contingency fit", 'mission'],
        ['meridian_core', "Meridian Core", "A silent lunar relic that remains aligned to an unknown celestial meridian", 'archaeology'],
        ['martian_signal_prism', "Martian Signal Prism", "A crystalline transmitter repeating an incomplete coordinate sequence", 'archaeology'],
        ['venusian_pressure_seal', "Venusian Pressure Seal", "An alien seal still holding an impossible internal pressure", 'archaeology'],
        ['burrower_carapace', "Burrower Carapace", "A heat-scored plate shed by something vast beneath the Martian crust", 'archaeology'],
        ['jovian_arena_standard', "Jovian Arena Standard", "A banner-crest salvaged from a coliseum that drifts, empty and silent, in Jupiter's storms", 'archaeology']
]

StartupEvents.registry('item', event => {
    SPACE_INDUSTRY_ITEMS.forEach(([id, name, tooltip, family]) => {
        event.create(id)
            .displayName(name)
            .texture(`kubejs:item/space_industry/${id}`)
            .tooltip(`§7${tooltip}`)
            .tooltip(`§8Infinite Domain aerospace component · ${family.replace('_', ' ')}`)
    })
})

StartupEvents.registry('block', event => {
    const ores = [
        ['moon_ilmenite_ore', "Lunar Ilmenite"],
        ['moon_anorthosite_ore', "Lunar Anorthosite"],
        ['moon_kreep_ore', "Lunar KREEP Deposit"],
        ['moon_helium_regolith', "Helium-Bearing Lunar Regolith"],
        ['moon_silicate_ore', "Lunar Silicate Deposit"],
        ['mars_hematite_ore', "Martian Hematite"],
        ['mars_sulfate_ore', "Martian Sulfate Deposit"],
        ['mars_perchlorate_ore', "Martian Perchlorate Deposit"],
        ['mars_nickel_cobalt_ore', "Martian Nickel-Cobalt Deposit"],
        ['mars_brine_ore', "Hydrated Martian Brine"],
        ['mars_silicate_ore', "Martian Silicate Deposit"],
        ['venus_sulfur_ore', "Venusian Sulfur Deposit"],
        ['venus_vanadium_ore', "Venusian Vanadium Deposit"],
        ['venus_tungsten_ore', "Venusian Tungsten Deposit"],
        ['venus_refractory_ore', "Venusian Refractory Deposit"]
    ]
    ores.forEach(([id, name]) => {
        event.create(id)
            .displayName(name)
            .texture(`kubejs:block/space_industry/${id}`)
            .stoneSoundType()
            .hardness(5.5)
            .resistance(8.0)
            .requiresTool()
    })
})
