from __future__ import annotations

import math
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "kubejs/data/infinite_domain/function/admin/prepare_spawn_hospital_terrain.mcfunction"

# The authored hospital entrance meets the world at Y=61. The surrounding
# Wasteland surface settles around sea level (Y=63), so the apron rises through
# two broad one-block grades instead of terminating in a vertical platform edge.
BANDS = [
    (48, 63, "outer blend"),
    (42, 62, "middle blend"),
    (35, 61, "hospital apron"),
]


def extent(radius: int, z: int) -> tuple[int, int] | None:
    if abs(z) > radius:
        return None
    half = math.isqrt(radius * radius - z * z)
    return -half, half


def subtract(outer: tuple[int, int], inner: tuple[int, int] | None) -> list[tuple[int, int]]:
    if inner is None:
        return [outer]
    result = []
    if outer[0] < inner[0]:
        result.append((outer[0], inner[0] - 1))
    if inner[1] < outer[1]:
        result.append((inner[1] + 1, outer[1]))
    return result


def commands_for_segment(x1: int, x2: int, z: int, surface_y: int) -> list[str]:
    return [
        f"execute in minecraft:overworld run fill {x1} {surface_y + 1} {z} {x2} 103 {z} minecraft:air",
        f"execute in minecraft:overworld run fill {x1} 48 {z} {x2} {surface_y - 2} {z} minecraft:stone",
        f"execute in minecraft:overworld run fill {x1} {surface_y - 1} {z} {x2} {surface_y - 1} {z} minecraft:dirt",
        f"execute in minecraft:overworld run fill {x1} {surface_y} {z} {x2} {surface_y} {z} minecraft:coarse_dirt",
    ]


def main() -> None:
    lines = [
        "# GENERATED by scripts/generate_spawn_hospital_terrain.py. Do not hand-edit.",
        "# One-shot terrain preparation for the completed spawn hospital.",
        "# Core surface Y=61; broad transition bands rise through Y=62 to the",
        "# Wasteland sea-level surface at Y=63. Terrain outside radius 48 is untouched.",
        "# Horizontal row segments keep every fill safely below the command volume limit.",
        "",
    ]

    for band_index, (radius, surface_y, label) in enumerate(BANDS):
        inner_radius = BANDS[band_index + 1][0] if band_index + 1 < len(BANDS) else None
        lines.append(f"# {label}: radius {radius}, surface Y={surface_y}")
        for z in range(-radius, radius + 1):
            outer = extent(radius, z)
            inner = extent(inner_radius, z) if inner_radius is not None else None
            for x1, x2 in subtract(outer, inner):
                lines.extend(commands_for_segment(x1, x2, z, surface_y))
        lines.append("")

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    command_count = sum(1 for line in lines if line.startswith("execute "))
    print(f"Generated hospital terrain blend: {command_count} commands, core Y=61, edge Y=63")


if __name__ == "__main__":
    main()
