"""Lyran Research — infernal continuity facility (hero build).

The Nether landmark that replaces the relocated vanilla stronghold as the
pack's End-portal site.  See docs/LYRAN_RESEARCH.md for the design bible and
the narrative this geometry is expressing.

Authoring rules honoured here (STRUCTURE_REBUILD_SYSTEM_V2.md, Stage A.5):

  * every stair is a V2.encased_stairwell — never a bare diagonal of stair
    blocks; every ladder is a V2.ladder_shaft; every sign is a V2.backed_sign;
    every window is a V2.wall_window; damage is V2.fracture_breach, never a
    raw t.clear() box.
  * the envelope is sealed.  Each level gets a full floor slab and ceiling
    slab across its own footprint and every open cell is bounded by placed
    wall blocks, so the Nether lava ocean cannot reach an interior space.
  * one landmark NBT with direct jigsaw / structure_set / template_pool
    registration, following the alien family and the Continuity Far-Side
    Redoubt precedent.  The 84-structure wasteland corpus counts in
    structure_library/corpus-manifest.json are NOT touched.

Geometry source: structure_library/programs/lyran_research_level1_plan.json,
extracted from the printed reference map by scripts/lyran_extract_plan.py.
1 map cell = 1 block.
"""

from __future__ import annotations

import json
import random
import sys
import zlib
from collections import Counter
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import generate_wasteland_sites as WS  # Template, shell, door, partition_*, desk, bed
import structure_geometry_primitives_v2 as V2

Template = WS.Template
ROOT = Path(__file__).resolve().parents[2]
PLAN_PATH = ROOT / "dev/structure_library" / "programs" / "lyran_research_level1_plan.json"
PROGRAM_PATH = ROOT / "dev/structure_library" / "programs" / "lyran_research.json"
OUT_NBT = ROOT / "kubejs" / "data" / "infinite_domain" / "worldgen" / "structure" / "nether" / "lyran_research.nbt"

N = 91
PITCH = 8                 # 1 floor slab + 6 clear interior + 1 ceiling slab
LEVEL_COUNT = 5
SHAFT_TOP = 71            # template height 72; the shaft mouth is the only
SIZE = (N, SHAFT_TOP + 1, N)   # opening in the whole envelope

# --------------------------------------------------------------------------
# Palette — vanilla Nether-native, infernal-industrial (docs/LYRAN_RESEARCH.md §7)
# --------------------------------------------------------------------------
WALL = "minecraft:polished_blackstone_bricks"
WALL_CRACKED = "minecraft:cracked_polished_blackstone_bricks"
WALL_ACCENT = "minecraft:polished_blackstone"
WALL_CHISEL = "minecraft:chiseled_polished_blackstone"
FLOOR_PUBLIC = "minecraft:smooth_basalt"
FLOOR_HALL = "minecraft:polished_blackstone"
FLOOR_SERVICE = "minecraft:blackstone"
CEILING = "minecraft:blackstone"
PACKING = "minecraft:netherrack"
LAMP_PUBLIC = "minecraft:soul_lantern"
LAMP_WORKS = "minecraft:lantern"
LAMP_FARM = "minecraft:shroomlight"
DOOR_MAT = "crimson"
SIGN = "minecraft:crimson_wall_sign"
GLASS = "minecraft:tinted_glass"

LOOT_DATA = "infinite_domain:chests/wasteland_data"
LOOT_INDUSTRIAL = "infinite_domain:chests/wasteland_industrial"
LOOT_HOME = "infinite_domain:chests/wasteland_home"

# --------------------------------------------------------------------------
# Levels.  All five reuse the same 91x91 bearing lattice; they differ in which
# region of it is excavated, and in what each room is for.
# --------------------------------------------------------------------------
NORTH, BAND, SOUTH = "north", "band", "south"

LEVELS = [
    {"key": "deep_works",   "title": "Deep Works",          "y": 0,  "regions": {SOUTH}},
    {"key": "laboratories", "title": "The Laboratories",    "y": 8,  "regions": {BAND, SOUTH}},
    {"key": "concourse",    "title": "The Concourse",       "y": 16, "regions": {NORTH, BAND, SOUTH}},
    {"key": "habitation",   "title": "Habitation Terraces", "y": 24, "regions": {NORTH, BAND}},
    {"key": "anchorage",    "title": "The Anchorage",       "y": 32, "regions": {NORTH}},
]
LEVEL_BY_KEY = {lv["key"]: lv for lv in LEVELS}


def _seed(key: str) -> int:
    """Stable per-level seed.

    Python's built-in hash() for str is salted per process, so using it here
    made the generator emit a different building on every run.  A structure
    that cannot be regenerated byte-for-byte is not reviewable, so seeding is
    done with a fixed checksum instead.
    """
    return zlib.crc32(key.encode("utf-8"))


def region_of(z: int) -> str:
    if z <= 30:
        return NORTH
    if z <= 59:
        return BAND
    return SOUTH


# --------------------------------------------------------------------------
# Vertical circulation.  Rects are (x1, z1, x2, z2) and must give a straight
# 8-tread run plus landings; each connects level `base` to the level above it.
# The first three sit on the reference map's own printed Up/Down markers.
# --------------------------------------------------------------------------
STAIRWELLS = [
    # key,           rect,                 run axis/facing, from-level
    ("north_ascent",  (53, 1, 59, 11), "south", "concourse"),    # map "Up",   off Room 3
    ("north_ascent2", (53, 1, 59, 11), "south", "habitation"),   # continues to the Anchorage
    ("west_descent",  (2, 43, 9, 53),  "south", "laboratories"), # map "Down", west of Room 26
    ("east_descent",  (58, 50, 64, 60), "south", "laboratories"),# map "Down", south of Room 34
    ("deep_descent",  (31, 76, 39, 86), "south", "deep_works"),  # Ossuary -> Laboratories
]

# The armoured climb from the Anchorage roof to a bastion head standing above
# the Y=64 lava sea.  Placed at world Y=10, its mouth opens at world Y 81.
SHAFT_RECT = (53, 2, 59, 8)


# --------------------------------------------------------------------------
# Room programs.  Room numbers are the numbers printed on the reference map.
# --------------------------------------------------------------------------
CONCOURSE_ROOMS = {
    1: ("The Muster Ring", "memorial"),      2: ("Chapter House", "council"),
    3: ("Ascent Hall", "stairhall"),         4: ("The Registry", "archive"),
    5: ("Rotunda of Returns", "memorial"),   6: ("Warden's Office", "office"),
    7: ("The Signal Ring", "control"),       8: ("Records Vault", "archive"),
    9: ("Dispatch", "office"),               10: ("The Clinic", "clinic"),
    11: ("Apothecary", "clinic"),            12: ("West Reclamation", "reclaim"),
    13: ("Culture Hall", "farm"),            14: ("Cistern Ring", "cistern"),
    15: ("Concourse Well", "hall"),          16: ("Refectory", "refectory"),
    17: ("The Long Hall", "hall"),           18: ("Store Rooms", "storage"),
    19: ("East Magazine", "storage"),        20: ("Provisioning", "storage"),
    21: ("THE GATE CHAMBER", "gate"),        22: ("Gate Antechamber", "vesting"),
    23: ("The Eye Reliquary", "reliquary"),  24: ("Crucible Shop", "workshop"),
    25: ("Glass & Lens Works", "workshop"),  26: ("West Stair Hall", "stairhall"),
    27: ("Machine Hall", "machine"),         28: ("East Reclamation", "reclaim"),
    29: ("The Kiln Ring", "kiln"),           30: ("Gate Control", "control"),
    31: ("Instrument Shop", "workshop"),     32: ("Quarantine Cells", "cells"),
    33: ("Cartography", "archive"),          34: ("East Stair Hall", "stairhall"),
    35: ("Waste Sorting", "reclaim"),        36: ("The Warren", "warren"),
    37: ("The Commons", "refectory"),        38: ("Dormitory A", "dormitory"),
    39: ("Dormitory B", "dormitory"),        40: ("The Creche", "creche"),
    41: ("Infirmary", "clinic"),             42: ("Mortuary", "mortuary"),
    43: ("The Ossuary", "ossuary"),          44: ("Shrine of the Return", "shrine"),
    45: ("Pilgrim Cells", "cells"),          46: ("The Last Ward", "lastward"),
}

# Derived levels reuse the same room shells with a different program.  Only the
# rooms in each level's excavated region are used.
ANCHORAGE_ROOMS = {
    1: ("The Watch", "control"),           2: ("Blast Lock", "airlock"),
    3: ("Shaft Head", "stairhall"),        4: ("Decontamination", "airlock"),
    5: ("Muster Well", "hall"),            6: ("Watch Office", "office"),
    7: ("The Dead Mooring", "storage"),    8: ("Cargo Hall West", "storage"),
    9: ("Cargo Hall East", "storage"),
}
HABITATION_ROOMS = {
    1: ("Terrace Rotunda", "hall"),        2: ("Married Quarters", "dormitory"),
    3: ("Upper Ascent", "stairhall"),      4: ("Dormitory C", "dormitory"),
    5: ("Wash House", "reclaim"),          6: ("Steward's Room", "office"),
    7: ("Upper Commons", "refectory"),     8: ("Dormitory D", "dormitory"),
    9: ("Dormitory E", "dormitory"),       10: ("Nursery", "creche"),
    11: ("Schoolroom", "archive"),         12: ("Farm Hall West", "farm"),
    13: ("Farm Hall Two", "farm"),         14: ("Upper Cistern", "cistern"),
    15: ("Gate Gallery North", "gallery"), 16: ("Refectory Annex", "refectory"),
    17: ("Laundry", "reclaim"),            18: ("Linen Store", "storage"),
    19: ("Upper Magazine", "storage"),     20: ("Farm Hall Three", "farm"),
    21: ("GATE VOID", "gatevoid"),         22: ("Gate Gallery East", "gallery"),
    23: ("Vestry", "shrine"),              24: ("Weaving Room", "workshop"),
    25: ("Potters", "workshop"),           26: ("West Landing", "stairhall"),
    27: ("Spore Beds", "farm"),            28: ("Upper Reclamation", "reclaim"),
    29: ("Bath Ring", "cistern"),          30: ("Gate Gallery South", "gallery"),
    31: ("Repair Shop", "workshop"),       32: ("Sick Cells", "cells"),
    33: ("Reading Room", "archive"),       34: ("East Landing", "stairhall"),
    35: ("Compost Hall", "farm"),          36: ("Upper Warren", "warren"),
}
LABORATORY_ROOMS = {
    10: ("Metrology West", "lab"),         11: ("Sounding Bench One", "lab"),
    12: ("Reagent Store", "storage"),      13: ("Specimen Hold", "cells"),
    14: ("Coolant Ring", "cistern"),       15: ("Anchor Gallery North", "gallery"),
    16: ("Blaze Crucible", "kiln"),        17: ("Assay Hall", "lab"),
    18: ("Sample Store", "storage"),       19: ("Powder Magazine", "storage"),
    20: ("Sounding Bench Two", "lab"),     21: ("THE ANCHOR WORKS", "anchor"),
    22: ("Anchor Gallery East", "gallery"),23: ("Calibration Cell", "control"),
    24: ("Furnace Row", "kiln"),           25: ("Optics Bench", "workshop"),
    26: ("West Landing", "stairhall"),     27: ("Apparatus Hall", "machine"),
    28: ("Condenser Bank", "reclaim"),     29: ("Annealing Ring", "kiln"),
    30: ("Anchor Control", "control"),     31: ("Fabrication", "workshop"),
    32: ("Containment Cells", "cells"),    33: ("Survey Office", "archive"),
    34: ("East Landing", "stairhall"),     35: ("Effluent Sorting", "reclaim"),
    36: ("Service Warren", "warren"),      37: ("Failed Apparatus", "graveyard"),
    38: ("Sample Store South", "storage"), 39: ("Cold Store", "storage"),
    40: ("Quiet Room", "cells"),           41: ("Field Infirmary", "clinic"),
    42: ("Disposal", "mortuary"),          43: ("Deep Stair Head", "stairhall"),
    44: ("Abandoned Chapel", "shrine"),    45: ("Store Cells", "storage"),
    46: ("Sealed Ward", "cells"),
}
DEEP_WORKS_ROOMS = {
    37: ("The Geothermal Tap", "geothermal"), 38: ("Tap Gallery West", "machine"),
    39: ("Tap Gallery East", "machine"),      40: ("The Foundry", "kiln"),
    41: ("Casting Floor", "workshop"),        42: ("Slag Hall", "graveyard"),
    43: ("Deep Stair Foot", "stairhall"),     44: ("Pump House", "machine"),
    45: ("Fuel Cells", "storage"),            46: ("THE SINK", "sink"),
}
PROGRAMS = {
    "anchorage": ANCHORAGE_ROOMS,
    "habitation": HABITATION_ROOMS,
    "concourse": CONCOURSE_ROOMS,
    "laboratories": LABORATORY_ROOMS,
    "deep_works": DEEP_WORKS_ROOMS,
}

# Lighting temperature tells the player which part of the colony they are in.
LAMP_BY_KIND = {
    "farm": LAMP_FARM, "cistern": LAMP_FARM, "kiln": LAMP_WORKS,
    "workshop": LAMP_WORKS, "machine": LAMP_WORKS, "geothermal": LAMP_WORKS,
    "reclaim": LAMP_WORKS, "graveyard": LAMP_WORKS, "sink": LAMP_WORKS,
    "warren": LAMP_WORKS, "lab": LAMP_WORKS,
}

# Rooms that get iron doors instead of crimson ones on a given level.
SECURE_KINDS = {"cells", "airlock", "reliquary", "anchor", "gate"}


# --------------------------------------------------------------------------
# Plan access helpers
# --------------------------------------------------------------------------
class Plan:
    def __init__(self, path: Path):
        raw = json.loads(path.read_text(encoding="utf-8"))
        self.grid = raw["grid"]
        self.open: set[tuple[int, int]] = {
            (x, z) for z in range(N) for x in range(N) if self.grid[z][x] == "."
        }
        self.doors = [(d["x"], d["z"], d["axis"]) for d in raw["doors"]]
        self.rooms = {
            int(k): {
                "cells": {(x, z) for x, z in v["cells"]},
                "bounds": v["bounds"],
                "label": tuple(v["label"]),
                "area": v["area"],
            }
            for k, v in raw["rooms"].items()
        }
        self.orphans = {(x, z) for x, z in raw["orphan_cells"]}

    def is_open(self, x: int, z: int) -> bool:
        return (x, z) in self.open


def room_cells_in(plan: Plan, room: int, regions: set[str]) -> set[tuple[int, int]]:
    return {(x, z) for x, z in plan.rooms[room]["cells"] if region_of(z) in regions}


def interior_of(cells: set[tuple[int, int]], plan: Plan) -> list[tuple[int, int]]:
    """Cells with open floor on all four sides — safe for freestanding furniture."""
    return sorted(
        c for c in cells
        if all(plan.is_open(c[0] + dx, c[1] + dz) for dx, dz in ((1, 0), (-1, 0), (0, 1), (0, -1)))
    )


def wall_adjacent_of(cells: set[tuple[int, int]], plan: Plan) -> list[tuple[int, int, str]]:
    """Open cells touching a wall, with the facing that points away from it."""
    out = []
    for x, z in sorted(cells):
        for (dx, dz), facing in (((0, -1), "south"), ((0, 1), "north"), ((-1, 0), "east"), ((1, 0), "west")):
            if not plan.is_open(x + dx, z + dz):
                out.append((x, z, facing))
                break
    return out


# --------------------------------------------------------------------------
# Level shell
# --------------------------------------------------------------------------
def build_level_shell(t: Template, plan: Plan, level: dict, holes: set[tuple[int, int]]) -> set[tuple[int, int]]:
    """Floor slab, ceiling slab and wall columns for one level.

    `holes` are cells where the floor and ceiling slabs must be omitted so a
    stairwell or the Gate Chamber void can pass vertically through them.
    Returns the set of open floor cells actually excavated on this level.
    """
    y = level["y"]
    regions = level["regions"]
    rng = random.Random(_seed(level["key"]))

    active = {(x, z) for (x, z) in plan.open if region_of(z) in regions}

    # Wall cells are the closed cells touching excavated floor (8-connected so
    # corners are sealed too) — this is what makes the envelope lava-tight.
    walls: set[tuple[int, int]] = set()
    for x, z in active:
        for dx in (-1, 0, 1):
            for dz in (-1, 0, 1):
                nx, nz = x + dx, z + dz
                if 0 <= nx < N and 0 <= nz < N and not plan.is_open(nx, nz):
                    walls.add((nx, nz))

    footprint = active | walls

    # Floor slab.  Public halls read differently from service spaces.
    for x, z in footprint:
        if (x, z) in holes:
            continue
        if (x, z) in walls:
            block = WALL_ACCENT
        elif region_of(z) == BAND and 30 <= x <= 60:
            block = FLOOR_HALL
        else:
            block = FLOOR_PUBLIC if (x, z) in active else FLOOR_SERVICE
        t.set(x, y, z, block)

    # Excavate the rooms.  This is not optional: a structure template only
    # removes what it explicitly places, so without an air column every
    # "room" generates as solid Nether rock with a decorative wall grid
    # buried in it.  The interior air IS the building.
    for x, z in active:
        t.clear((x, y + 1, z), (x, y + 6, z))

    # Ceiling slab.
    for x, z in footprint:
        if (x, z) in holes:
            continue
        t.set(x, y + 7, z, CEILING)

    # Wall columns, with age-cracking that increases with depth.
    crack_rate = {"deep_works": 0.22, "laboratories": 0.14, "concourse": 0.06,
                  "habitation": 0.10, "anchorage": 0.16}[level["key"]]
    for x, z in walls:
        for wy in range(y + 1, y + 7):
            block = WALL_CRACKED if rng.random() < crack_rate else WALL
            t.set(x, wy, z, block)

    # A course of packing rock behind the outermost wall ring, so the building
    # never presents a bare one-block skin to open lava.
    for x, z in walls:
        for dx in (-1, 0, 1):
            for dz in (-1, 0, 1):
                nx, nz = x + dx, z + dz
                if not (0 <= nx < N and 0 <= nz < N):
                    continue
                if (nx, nz) in footprint or (nx, nz) in holes:
                    continue
                for wy in range(y, y + 8):
                    t.set(nx, wy, nz, PACKING)

    return active


def build_doors(t: Template, plan: Plan, level: dict, program: dict, active: set[tuple[int, int]],
                skip: set[tuple[int, int]]) -> tuple[set[tuple[int, int]], set[tuple[int, int]]]:
    """Hang a door in every printed doorway inside this level's footprint.

    Derived levels re-partition the same lattice: the colony walled openings up
    and knocked others through repeatedly over four hundred years, which is why
    the plan is shared but the door set is not.
    """
    y = level["y"]
    rng = random.Random(0x1EA5 ^ _seed(level["key"]))
    room_kind: dict[tuple[int, int], str] = {}
    for num, (_name, kind) in program.items():
        for c in room_cells_in(plan, num, level["regions"]):
            room_kind[c] = kind
    walled_up: set[tuple[int, int]] = set()
    doored: set[tuple[int, int]] = set()

    for x, z, axis in plan.doors:
        if (x, z) not in active or (x, z) in skip:
            continue
        roll = rng.random()
        if roll < 0.12 and level["key"] != "concourse":
            # Walled up.  Solid, and it reads as a later blocking course.
            for wy in range(y + 1, y + 7):
                t.set(x, wy, z, WALL_CRACKED)
            walled_up.add((x, z))
            continue
        if roll < 0.30:
            continue  # left as an open archway
        neighbours = [room_kind.get((x + dx, z + dz)) for dx, dz in ((1, 0), (-1, 0), (0, 1), (0, -1))]
        secure = any(k in SECURE_KINDS for k in neighbours if k)
        facing = "east" if axis == "x" else "south"
        WS.door(t, x, y + 1, z, facing, DOOR_MAT)
        if secure:
            # Controlled access is expressed with a chiselled architrave, NOT
            # with an iron door.  An iron door in a generated structure needs
            # redstone the player has no way to supply, so it is not a secure
            # room, it is a room nobody can ever enter.
            for dx, dz in (((0, -1), (0, 1)) if axis == "x" else ((-1, 0), (1, 0))):
                for wy in range(y + 1, y + 4):
                    if solid_at(t, x + dx, wy, z + dz):
                        t.set(x + dx, wy, z + dz, WALL_CHISEL)
        doored.add((x, z))
    return walled_up, doored


def repair_circulation(t: Template, level: dict, active: set[tuple[int, int]],
                       walled_up: set[tuple[int, int]], doored: set[tuple[int, int]]) -> dict[str, int]:
    """Guarantee every excavated cell on this level is actually reachable.

    Four hundred years of re-partitioning is good fiction, but a blocking
    course that happens to be the only way into a nine-cell corridor stub is
    just an unreachable room.  This pass re-opens exactly the blockages that
    isolate something, and downgrades a door to an open archway where the
    pocket behind it is too small to be a room at all — the two conditions
    check_room_composition flags.
    """
    from collections import deque
    y = level["y"]
    reopened = 0
    demoted = 0

    def components(passable: set[tuple[int, int]]) -> list[set[tuple[int, int]]]:
        seen: set[tuple[int, int]] = set()
        out = []
        for start in passable:
            if start in seen:
                continue
            comp = {start}
            seen.add(start)
            q = deque([start])
            while q:
                cx, cz = q.popleft()
                for dx, dz in ((1, 0), (-1, 0), (0, 1), (0, -1)):
                    n = (cx + dx, cz + dz)
                    if n in passable and n not in seen:
                        seen.add(n)
                        comp.add(n)
                        q.append(n)
            out.append(comp)
        return out

    # 1. A doored pocket smaller than a room becomes an archway instead.
    for comp in components(active - walled_up - doored):
        if len(comp) >= 4:
            continue
        for cx, cz in comp:
            for dx, dz in ((1, 0), (-1, 0), (0, 1), (0, -1)):
                n = (cx + dx, cz + dz)
                if n in doored:
                    t.clear((n[0], y + 1, n[1]), (n[0], y + 2, n[1]))
                    doored.discard(n)
                    demoted += 1

    # 2. Re-open blocking courses until the level is one connected space.
    guard = 0
    while guard < 200:
        guard += 1
        comps = components(active - walled_up)
        if len(comps) <= 1:
            break
        comps.sort(key=len, reverse=True)
        main = comps[0]
        bridged = False
        for cell in sorted(walled_up):
            touches = set()
            for dx, dz in ((1, 0), (-1, 0), (0, 1), (0, -1)):
                n = (cell[0] + dx, cell[1] + dz)
                for i, comp in enumerate(comps):
                    if n in comp:
                        touches.add(i)
            if len(touches) > 1 or (touches and 0 in touches and len(comps) > 1 and len(touches) == 1 and False):
                t.clear((cell[0], y + 1, cell[1]), (cell[0], y + 2, cell[1]))
                walled_up.discard(cell)
                reopened += 1
                bridged = True
                break
        if not bridged:
            break
    return {"reopened": reopened, "archways": demoted}


# --------------------------------------------------------------------------
# Vertical circulation
# --------------------------------------------------------------------------
def stairwell_holes(rect: tuple[int, int, int, int], margin: int = 0) -> set[tuple[int, int]]:
    """Footprint of a vertical shaft, optionally grown by a margin.

    The margin exists because `encased_stairwell` builds its landings
    `landing_depth` blocks *beyond* the run it was given, so reserving only
    the nominal rect would let a prop land on a stair landing.
    """
    x1, z1, x2, z2 = rect
    return {
        (x, z)
        for x in range(x1 - margin, x2 + margin + 1)
        for z in range(z1 - margin, z2 + margin + 1)
    }


def solid_at(t: Template, x: int, y: int, z: int) -> bool:
    """True when a real, non-air block has actually been placed at this cell.

    Every prop is guarded on this: furniture needs a floor under it and a
    hanging lantern needs a ceiling over it.  Without the guard, a prop
    placed where a stair or the ascent shaft later cut the slab away becomes
    a floating block — which is precisely what check_structural_connectivity
    exists to catch.
    """
    entry = t.blocks.get((x, y, z))
    if entry is None:
        return False
    return t.palette[entry[0]]["Name"] != "minecraft:air"


def build_stairwell(t: Template, rect: tuple[int, int, int, int], y: int) -> None:
    """One straight 8-tread encased run carrying a full level of pitch.

    The run is cut through slabs the shell pass already placed, rather than
    through pre-punched holes: `encased_stairwell` clears three blocks of
    headroom over every tread, and that is exactly what opens this level's
    ceiling and the next level's floor — only where the stair physically
    passes.  Pre-holing the whole rect instead left an eleven-block pit in
    the floor of the level above, which is why it is not done that way.

    Treads run y+1..y+8; the top landing plate lands at y+8, the floor plane
    of the level above.
    """
    x1, z1, x2, z2 = rect
    cx = (x1 + x2) // 2
    V2.encased_stairwell(t, cx, y + 1, z1 + 2, 8, "south",
                         block="minecraft:blackstone_stairs", wall=WALL, width=2, landing_depth=2)
    # Level plate at the stair head.  backed_sign guarantees a backing block,
    # but a single backing block floating in the middle of a room is itself a
    # connectivity failure — so the backing is a full pilaster from the floor.
    sx, sz = cx + 2, z1 + 1
    t.fill((sx, y + 1, sz - 1), (sx, y + 6, sz - 1), WALL)
    V2.backed_sign(t, sx, y + 3, sz, "south", SIGN, backing=WALL)


def build_ascent_shaft(t: Template) -> None:
    """Armoured ladder climb from the Anchorage roof to a bastion head that
    stands clear of the Y=64 lava sea, and is the only opening in the envelope."""
    x1, z1, x2, z2 = SHAFT_RECT
    top_y = LEVELS[-1]["y"] + PITCH  # 40 — the Anchorage ceiling plane
    cx, cz = (x1 + x2) // 2, (z1 + z2) // 2

    # Two-thick armoured casing all the way up.
    # Casing starts at the Anchorage ceiling plane.  Running it down through
    # the Anchorage interior instead builds a five-by-five tube straight
    # through the arrival level, walling the ladder off from the stair hall it
    # is supposed to open onto.
    for y in range(top_y - 1, SHAFT_TOP + 1):
        for x in range(x1 - 1, x2 + 2):
            for z in range(z1 - 1, z2 + 2):
                on_skin = x in (x1 - 1, x1, x2, x2 + 1) or z in (z1 - 1, z1, z2, z2 + 1)
                if on_skin:
                    t.set(x, y, z, WALL if (x + z + y) % 11 else WALL_CRACKED)
    # Hollow core.
    t.clear((x1 + 1, LEVELS[-1]["y"] + 1, z1 + 1), (x2 - 1, SHAFT_TOP, z2 - 1))

    # Ladder run with rest landings every eight blocks.  It starts on the
    # Anchorage floor, not at the Anchorage ceiling: a climb that stops one
    # level short leaves arrivals with an unannounced six-block drop.
    y = LEVELS[-1]["y"] + 1
    while y < SHAFT_TOP - 1:
        run = min(8, SHAFT_TOP - 1 - y)
        V2.ladder_shaft(t, cx, y, z1 + 1, run, "south", backing=WALL)
        y += run
        if y < SHAFT_TOP - 2:
            # A rest landing, with a two-cell opening: the ladder column plus
            # the cell a climber steps off onto.  A one-cell hole plugged by
            # the ladder block itself reads to the room-composition check as a
            # sealed compartment, because a ladder is not air.
            for x in range(x1 + 1, x2):
                for z in range(z1 + 1, z2):
                    if (x, z) not in ((cx, z1 + 1), (cx, z1 + 2)):
                        t.set(x, y, z, "minecraft:blackstone")
            t.clear((cx, y, z1 + 1), (cx, y, z1 + 2))

    # Bastion head: a parapet standing above the lava, so the site reads as a
    # landmark from a distance instead of a hole in the floor.
    for x in range(x1 - 2, x2 + 3):
        for z in range(z1 - 2, z2 + 3):
            ring = x in (x1 - 2, x2 + 2) or z in (z1 - 2, z2 + 2)
            if ring:
                t.fill((x, SHAFT_TOP - 3, z), (x, SHAFT_TOP - 1, z), WALL)
            elif not (x1 < x < x2 and z1 < z < z2):
                t.set(x, SHAFT_TOP - 3, z, FLOOR_HALL)
    for cxx, czz in ((x1 - 2, z1 - 2), (x2 + 2, z1 - 2), (x1 - 2, z2 + 2), (x2 + 2, z2 + 2)):
        t.fill((cxx, SHAFT_TOP - 3, czz), (cxx, SHAFT_TOP, czz), WALL_CHISEL)
        t.set(cxx, SHAFT_TOP, czz, LAMP_PUBLIC, hanging="false", waterlogged="false")
    V2.backed_sign(t, cx, SHAFT_TOP - 2, z1 - 1, "north", SIGN, backing=WALL)


# --------------------------------------------------------------------------
# The Gate Chamber
# --------------------------------------------------------------------------
def build_gate_chamber(t: Template, plan: Plan) -> set[tuple[int, int]]:
    """Room 21 on the Concourse: the End portal on a dais over a lava well,
    open to a gallery ring on the Habitation level above.

    Returns the cells whose Habitation-level floor slab must be omitted.
    """
    y = LEVEL_BY_KEY["concourse"]["y"]
    cells = plan.rooms[21]["cells"]
    x1, z1, x2, z2 = plan.rooms[21]["bounds"]
    cx, cz = 35, 43  # measured centre of the printed nine-block circle

    # Lava well under a raised dais — the aperture was found in the rock and
    # the colony built the floor around it.
    t.fill((cx - 3, y, cz - 3), (cx + 3, y, cz + 3), "minecraft:polished_blackstone_bricks")
    t.fill((cx - 1, y, cz - 1), (cx + 1, y, cz + 1), "minecraft:lava", level="0")
    t.fill((cx - 2, y + 1, cz - 2), (cx + 2, y + 1, cz + 2), "minecraft:air")

    # Twelve end portal frames around the 3x3 aperture.  Four already hold the
    # colony's own eyes — four hundred years of the Egress Programme's total
    # progress — leaving the rest for the player.
    seated = {(cx - 1, cz - 2), (cx + 1, cz - 2), (cx - 2, cz + 1), (cx + 2, cz - 1)}
    frames = []
    for d in (-1, 0, 1):
        frames.append(((cx + d, cz - 2), "south"))
        frames.append(((cx + d, cz + 2), "north"))
        frames.append(((cx - 2, cz + d), "east"))
        frames.append(((cx + 2, cz + d), "west"))
    for (fx, fz), facing in frames:
        t.set(fx, y + 1, fz, "minecraft:end_portal_frame", facing=facing,
              eye="true" if (fx, fz) in seated else "false")

    # Walkway ring, monitoring stations and the chamber's own lighting.
    for x, z in cells:
        if abs(x - cx) <= 2 and abs(z - cz) <= 2:
            continue
        t.set(x, y, z, FLOOR_HALL)
    for wx, wz, facing in wall_adjacent_of(cells, plan)[::3]:
        t.set(wx, y + 1, wz, "minecraft:lodestone")
    for lx, lz in ((cx - 4, cz), (cx + 4, cz), (cx, cz - 4), (cx, cz + 4)):
        if (lx, lz) in cells:
            t.set(lx, y + 6, lz, LAMP_PUBLIC, hanging="true", waterlogged="false")

    # Double height: pierce the Concourse ceiling across the chamber, and hand
    # back the footprint so the Habitation floor slab is omitted there too.
    void = {(x, z) for x, z in cells if abs(x - cx) <= 3 and abs(z - cz) <= 3}
    for x, z in void:
        t.set(x, y + 7, z, "minecraft:air")
    return void


def build_gate_gallery(t: Template, plan: Plan, void: set[tuple[int, int]]) -> None:
    """Habitation-level ring around the Gate void: a real balustrade, not a hole."""
    y = LEVEL_BY_KEY["habitation"]["y"]
    cells = plan.rooms[21]["cells"]
    for x, z in cells:
        if (x, z) in void:
            continue
        t.set(x, y, z, FLOOR_HALL)
    for x, z in void:
        for dx, dz in ((1, 0), (-1, 0), (0, 1), (0, -1)):
            nx, nz = x + dx, z + dz
            if (nx, nz) in cells and (nx, nz) not in void:
                t.set(nx, y + 1, nz, "minecraft:polished_blackstone_slab", type="bottom", waterlogged="false")


# --------------------------------------------------------------------------
# Room furnishing
# --------------------------------------------------------------------------
def furnish(t: Template, plan: Plan, level: dict, num: int, name: str, kind: str,
            cells: set[tuple[int, int]], rng: random.Random) -> None:
    if not cells:
        return
    y = level["y"]
    inner = interior_of(cells, plan)
    walls = wall_adjacent_of(cells, plan)
    if not inner:
        inner = sorted(cells)

    def spot(i: int) -> tuple[int, int]:
        return inner[i % len(inner)]

    def standable(px: int, pz: int) -> bool:
        """A prop needs a real floor beneath it and clear air at its own cell."""
        return solid_at(t, px, y, pz) and not solid_at(t, px, y + 1, pz)

    # Every room gets light, hung from its own ceiling — but only where a
    # ceiling still exists after circulation cut through the slabs.
    lamp = LAMP_BY_KIND.get(kind, LAMP_PUBLIC)
    for i in range(max(1, len(cells) // 18)):
        lx, lz = spot(i * 7 + 3)
        if not solid_at(t, lx, y + 7, lz) or solid_at(t, lx, y + 6, lz):
            continue
        if lamp == LAMP_FARM:
            t.set(lx, y + 6, lz, LAMP_FARM)
        else:
            t.set(lx, y + 6, lz, lamp, hanging="true", waterlogged="false")

    # Every room gets a name plate on a real backed wall.
    if walls:
        sx, sz, facing = walls[len(walls) // 2]
        V2.backed_sign(t, sx, y + 3, sz, facing, SIGN, backing=WALL)

    def put(i: int, block: str, **props):
        px, pz = spot(i)
        if standable(px, pz):
            t.set(px, y + 1, pz, block, **props)

    def chest(i: int, table: str):
        px, pz = spot(i)
        if standable(px, pz):
            t.chest(px, y + 1, pz, table, "north")

    def lay_bed(px: int, pz: int, colour: str):
        if standable(px, pz) and standable(px, pz + 1):
            WS.bed(t, px, y + 1, pz, "south", colour)

    if kind == "archive":
        for i in range(0, len(inner), 4):
            put(i, "minecraft:lectern", facing="north", has_book="false", powered="false")
        chest(1, LOOT_DATA)
        chest(len(inner) // 2, LOOT_DATA)
    elif kind == "memorial":
        for i in range(0, len(inner), 3):
            put(i, "minecraft:polished_blackstone_slab", type="bottom", waterlogged="false")
        for wx, wz, facing in walls[::2]:
            V2.backed_sign(t, wx, y + 2, wz, facing, SIGN, backing=WALL)
    elif kind == "council":
        for i, c in enumerate(inner):
            if i % 2 == 0:
                t.set(c[0], y + 1, c[1], "minecraft:polished_blackstone_slab", type="bottom", waterlogged="false")
        put(0, "minecraft:lectern", facing="north", has_book="false", powered="false")
    elif kind in ("office", "control"):
        dx_, dz_ = spot(2)
        if standable(dx_, dz_) and standable(dx_ + 1, dz_):
            WS.desk(t, dx_, y + 1, dz_, "north")
        put(5, "minecraft:barrel", facing="up", open="false")
        chest(8, LOOT_DATA)
        for i in range(3, len(inner), 6):
            put(i, "minecraft:lodestone")
    elif kind == "clinic":
        for i in range(0, min(len(inner), 24), 5):
            lay_bed(*spot(i), "white")
        put(3, "minecraft:brewing_stand")
        chest(11, LOOT_HOME)
    elif kind == "dormitory":
        for i in range(0, min(len(inner), 30), 4):
            lay_bed(*spot(i), "brown")
        chest(2, LOOT_HOME)
    elif kind == "creche":
        for i in range(0, min(len(inner), 24), 3):
            lay_bed(*spot(i), "light_gray")
        chest(5, LOOT_HOME)
    elif kind in ("refectory", "hall"):
        for i in range(0, len(inner), 3):
            put(i, "minecraft:polished_blackstone_slab", type="bottom", waterlogged="false")
        put(1, "minecraft:smoker", facing="north", lit="false")
        put(4, "minecraft:cauldron")
    elif kind == "storage":
        for i in range(0, len(inner), 2):
            put(i, "minecraft:barrel", facing="up", open="false")
        chest(3, LOOT_INDUSTRIAL)
    elif kind in ("workshop", "machine"):
        for i in range(0, len(inner), 5):
            put(i, "minecraft:smithing_table")
        put(2, "minecraft:anvil", facing="north")
        put(7, "minecraft:grindstone", face="floor", facing="north")
        chest(4, LOOT_INDUSTRIAL)
    elif kind == "kiln":
        for i in range(0, len(inner), 4):
            put(i, "minecraft:blast_furnace", facing="north", lit="false")
        chest(6, LOOT_INDUSTRIAL)
    elif kind in ("reclaim", "cistern"):
        for i in range(0, len(inner), 4):
            put(i, "minecraft:cauldron")
        put(1, "minecraft:soul_sand")
    elif kind == "farm":
        for i in range(0, len(inner), 2):
            put(i, "minecraft:warped_wart_block" if i % 4 else "minecraft:nether_wart_block")
        for i in range(0, len(inner), 9):
            px, pz = spot(i + 1)
            if solid_at(t, px, y + 7, pz) and not solid_at(t, px, y + 6, pz):
                t.set(px, y + 6, pz, LAMP_FARM)
    elif kind == "cells":
        for i in range(0, len(inner), 6):
            lay_bed(*spot(i), "gray")
        chest(1, LOOT_HOME)
    elif kind == "lab":
        for i in range(0, len(inner), 4):
            put(i, "minecraft:brewing_stand")
        put(2, "minecraft:cartography_table")
        chest(5, LOOT_DATA)
    elif kind == "shrine":
        for i in range(0, len(inner), 3):
            put(i, "minecraft:polished_blackstone_slab", type="bottom", waterlogged="false")
        put(0, "minecraft:lodestone")
        for wx, wz, facing in walls[::3]:
            V2.backed_sign(t, wx, y + 2, wz, facing, SIGN, backing=WALL)
    elif kind in ("ossuary", "mortuary", "graveyard"):
        for i in range(0, len(inner), 2):
            put(i, "minecraft:bone_block", axis="y" if i % 3 else "x")
        chest(3, LOOT_DATA)
    elif kind == "reliquary":
        for i, c in enumerate(inner[:12]):
            put(i, "minecraft:end_portal_frame",
                facing=("north", "east", "south", "west")[i % 4], eye="false")
        chest(0, LOOT_DATA)
        for wx, wz, facing in walls[::2]:
            V2.backed_sign(t, wx, y + 2, wz, facing, SIGN, backing=WALL)
    elif kind == "vesting":
        for i in range(0, len(inner), 4):
            put(i, "minecraft:barrel", facing="up", open="false")
        chest(1, LOOT_INDUSTRIAL)
        chest(6, LOOT_HOME)
    elif kind == "anchor":
        for i in range(0, len(inner), 3):
            put(i, "minecraft:lodestone")
        put(1, "minecraft:respawn_anchor", charges="0")
        chest(4, LOOT_DATA)
    elif kind == "geothermal":
        for i in range(0, len(inner), 7):
            px, pz = spot(i)
            if solid_at(t, px, y, pz):
                t.set(px, y, pz, "minecraft:magma_block")
        put(2, "minecraft:blast_furnace", facing="north", lit="false")
    elif kind == "sink":
        for i in range(0, len(inner), 3):
            px, pz = spot(i)
            if solid_at(t, px, y, pz):
                t.set(px, y, pz, "minecraft:magma_block")
        chest(1, LOOT_DATA)
    elif kind == "airlock":
        for i in range(0, len(inner), 5):
            put(i, "minecraft:cauldron")
        chest(2, LOOT_INDUSTRIAL)
    elif kind == "gallery":
        for i in range(0, len(inner), 4):
            put(i, "minecraft:polished_blackstone_slab", type="bottom", waterlogged="false")
    elif kind == "lastward":
        put(0, "minecraft:lectern", facing="north", has_book="false", powered="false")
        chest(2, LOOT_DATA)
        chest(4, LOOT_HOME)
        for wx, wz, facing in walls[::2]:
            V2.backed_sign(t, wx, y + 2, wz, facing, SIGN, backing=WALL)
    elif kind == "warren":
        for i in range(0, len(inner), 8):
            put(i, "minecraft:barrel", facing="up", open="false")
    # stairhall / gatevoid / gate deliberately place nothing here.


# --------------------------------------------------------------------------
# Secret passage
# --------------------------------------------------------------------------
def build_bolt_hole(t: Template, plan: Plan) -> None:
    """The map's isolated 17-cell passage behind Room 44 — the Warden's
    bolt-hole.  It is given a genuine, unmarked opening rather than being left
    sealed: a sealed furnished pocket is both a lint hard-fail and, more to the
    point, a room no player can ever reach."""
    y = LEVEL_BY_KEY["concourse"]["y"]
    passage = sorted(c for c in plan.orphans if 55 <= c[0] <= 59 and 78 <= c[1] <= 87)
    if not passage:
        return
    for x, z in passage:
        t.fill((x, y + 1, z), (x, y + 6, z), "minecraft:air")
        t.set(x, y, z, FLOOR_SERVICE)
        t.set(x, y + 7, z, CEILING)
    # Knock a concealed opening through to the nearest Room 44 cell.
    px, pz = passage[0]
    for dx in range(1, 5):
        if (px - dx, pz) in plan.rooms[44]["cells"]:
            for gap in range(1, dx):
                t.fill((px - gap, y + 1, pz), (px - gap, y + 2, pz), "minecraft:air")
                t.set(px - gap, y, pz, FLOOR_SERVICE)
            break
    ex, ez = passage[-1]
    t.chest(ex, y + 1, ez, LOOT_DATA, "north")
    t.set(px, y + 1, pz, "minecraft:lectern", facing="north", has_book="false", powered="false")


# --------------------------------------------------------------------------
# Build
# --------------------------------------------------------------------------
def build() -> tuple[Template, dict]:
    plan = Plan(PLAN_PATH)
    t = Template(SIZE)

    # Only the Gate Chamber void is a genuine slab hole.  Stairwells cut their
    # own openings as they are built (see build_stairwell), so the shell stays
    # intact everywhere a stair does not physically pass through it.
    holes: dict[str, set[tuple[int, int]]] = {lv["key"]: set() for lv in LEVELS}
    gate_void = {(x, z) for x, z in plan.rooms[21]["cells"] if abs(x - 35) <= 3 and abs(z - 43) <= 3}
    holes["habitation"] |= gate_void

    active_by_level = {}
    for level in LEVELS:
        active_by_level[level["key"]] = build_level_shell(t, plan, level, holes[level["key"]])

    gate_void_built = build_gate_chamber(t, plan)
    build_gate_gallery(t, plan, gate_void_built)
    build_bolt_hole(t, plan)

    # Circulation before furnishing: a stairwell or the ascent shaft must win
    # every conflict against a prop, never the other way round.  Furnishing
    # then skips those footprints outright and guards each placement against
    # the geometry that actually exists.
    for _key, rect, _facing, from_key in STAIRWELLS:
        build_stairwell(t, rect, LEVEL_BY_KEY[from_key]["y"])
    build_ascent_shaft(t)

    reserved: set[tuple[int, int]] = set()
    for _key, rect, _facing, _from in STAIRWELLS:
        reserved |= stairwell_holes(rect, margin=3)
    reserved |= stairwell_holes(SHAFT_RECT, margin=2)

    for level in LEVELS:
        program = PROGRAMS[level["key"]]
        rng = random.Random(0x1EA50000 ^ _seed(level["key"]))
        for num, (name, kind) in program.items():
            cells = room_cells_in(plan, num, level["regions"]) - reserved
            furnish(t, plan, level, num, name, kind, cells, rng)

    # Doors last: a walled-up or re-hung door must override whatever the shell
    # pass left in that cell.  Then repair circulation, so no re-partitioning
    # roll can leave part of a level unreachable.
    repairs = {}
    for level in LEVELS:
        walled_up, doored = build_doors(
            t, plan, level, PROGRAMS[level["key"]], active_by_level[level["key"]], reserved)
        repairs[level["key"]] = repair_circulation(
            t, level, active_by_level[level["key"]] - reserved, walled_up, doored)

    sealed = seal_envelope(t)

    counts = Counter(t.palette[state]["Name"] for state, _ in t.blocks.values())
    stats = {
        "size": list(SIZE),
        "placed_blocks": len(t.blocks),
        "palette_states": len(t.palette),
        "modded_blocks": sum(c for b, c in counts.items() if not b.startswith("minecraft:")),
        "chests": counts.get("minecraft:chest", 0),
        "portal_frames": counts.get("minecraft:end_portal_frame", 0),
        "levels": {lv["key"]: len(active_by_level[lv["key"]]) for lv in LEVELS},
        "circulation_repairs": repairs,
        "envelope_seal_blocks": sealed,
    }
    return t, stats


def seal_envelope(t: Template) -> int:
    """Backstop the lava-tight guarantee.

    The shell pass builds a closed envelope, but every later operation that
    clears space — a stairwell cutting its headroom through a slab, the Gate
    Chamber piercing its ceiling, the bolt-hole being opened — can leave an
    interior air cell facing a cell this template never places.  In the Nether
    that cell is whatever worldgen put there, which is very often lava, and one
    such gap floods the level.  So after all construction, any unplaced cell an
    interior air cell can see is backfilled with rock.

    The bastion head and the shaft mouth are excluded: that opening is the
    entrance, and is meant to be open.
    """
    sx, sy, sz = t.size
    x1, z1, x2, z2 = SHAFT_RECT
    mouth_floor = SHAFT_TOP - 4

    def is_mouth(x: int, y: int, z: int) -> bool:
        return y >= mouth_floor and x1 - 3 <= x <= x2 + 3 and z1 - 3 <= z <= z2 + 3

    air = [pos for pos, (state, _n) in t.blocks.items()
           if t.palette[state]["Name"] == "minecraft:air"]
    backfill: set[tuple[int, int, int]] = set()
    for x, y, z in air:
        if is_mouth(x, y, z):
            continue
        for dx, dy, dz in ((1, 0, 0), (-1, 0, 0), (0, 1, 0), (0, -1, 0), (0, 0, 1), (0, 0, -1)):
            n = (x + dx, y + dy, z + dz)
            if not (0 <= n[0] < sx and 0 <= n[1] < sy and 0 <= n[2] < sz):
                continue
            if n in t.blocks or is_mouth(*n):
                continue
            backfill.add(n)
    for x, y, z in backfill:
        t.set(x, y, z, PACKING)
    return len(backfill)


def save(t: Template) -> None:
    blocks = []
    for pos, (state, nbt) in sorted(t.blocks.items(), key=lambda row: (row[0][1], row[0][2], row[0][0])):
        entry = {"pos": WS.NbtList(WS.TAG_INT, list(pos)), "state": state}
        if nbt:
            entry["nbt"] = nbt
        blocks.append(entry)
    WS.write_nbt(OUT_NBT, {
        "DataVersion": WS.DATA_VERSION,
        "size": WS.NbtList(WS.TAG_INT, list(t.size)),
        "palette": WS.NbtList(WS.TAG_COMPOUND, t.palette),
        "blocks": WS.NbtList(WS.TAG_COMPOUND, blocks),
        "entities": WS.NbtList(WS.TAG_COMPOUND, t.entities),
    })


def emit_program(plan: Plan) -> None:
    """Write the per-structure room / adjacency / circulation program.

    STRUCTURE_REBUILD_SYSTEM_V2 treats this as a required *generation input*,
    not documentation: it is the record of what each room is for, which is what
    makes the interior pass reviewable rather than a scatter of props.
    """
    doors_by_cell = {(x, z): axis for x, z, axis in plan.doors}

    def adjacency(num: int, regions: set[str]) -> list[int]:
        """Rooms reachable from this one through a printed doorway."""
        cells = room_cells_in(plan, num, regions)
        touching: set[int] = set()
        for x, z in cells:
            for dx, dz in ((1, 0), (-1, 0), (0, 1), (0, -1)):
                nx, nz = x + dx, z + dz
                if (nx, nz) not in doors_by_cell:
                    continue
                for ex, ez in ((nx + dx, nz + dz), (nx + dx * 2, nz + dz * 2)):
                    for other, meta in plan.rooms.items():
                        if other != num and (ex, ez) in meta["cells"]:
                            touching.add(other)
        return sorted(touching)

    levels = []
    for level in LEVELS:
        program = PROGRAMS[level["key"]]
        rooms = []
        for num, (name, kind) in sorted(program.items()):
            cells = room_cells_in(plan, num, level["regions"])
            if not cells:
                continue
            meta = plan.rooms[num]
            rooms.append({
                "map_room": num,
                "name": name,
                "kind": kind,
                "shape": "circular" if num in (1, 5, 7, 14, 15, 21, 29) else
                         "pentagonal" if num in (2, 23, 44) else "rectilinear",
                "bounds": meta["bounds"],
                "floor_cells": len(cells),
                "lighting": LAMP_BY_KIND.get(kind, LAMP_PUBLIC),
                "secure": kind in SECURE_KINDS,
                "adjacent_rooms": adjacency(num, level["regions"]),
            })
        levels.append({
            "key": level["key"],
            "title": level["title"],
            "local_y": level["y"],
            "world_y": level["y"] + 10,
            "regions": sorted(level["regions"]),
            "interior_height": 6,
            "rooms": rooms,
        })

    PROGRAM_PATH.parent.mkdir(parents=True, exist_ok=True)
    PROGRAM_PATH.write_text(json.dumps({
        "structure_id": "lyran_research",
        "display_name": "Lyran Research",
        "family": "nether_landmark",
        "asset_class": "structure",
        "doctrine": "structure_library/STRUCTURE_REBUILD_SYSTEM_V2.md",
        "design_document": "docs/LYRAN_RESEARCH.md",
        "reference_plan": "structure_library/programs/lyran_research_level1_plan.json",
        "template_size": list(SIZE),
        "placement": {
            "dimension": "minecraft:the_nether",
            "start_height_absolute": 10,
            "terrain_adaptation": "none",
            "sealed_envelope": True,
            "surface_opening": "ascent shaft mouth only",
        },
        "circulation": [
            {"key": key, "rect": list(rect), "from_level": from_key,
             "kind": "encased_stairwell", "rise": 8}
            for key, rect, _facing, from_key in STAIRWELLS
        ] + [{"key": "ascent_shaft", "rect": list(SHAFT_RECT),
              "from_level": "anchorage", "kind": "ladder_shaft",
              "rise": SHAFT_TOP - (LEVELS[-1]["y"] + PITCH) + 1}],
        "levels": levels,
        "loot_tables": sorted({LOOT_DATA, LOOT_INDUSTRIAL, LOOT_HOME}),
    }, indent=2) + "\n", encoding="utf-8", newline="\n")


if __name__ == "__main__":
    template, report = build()
    save(template)
    emit_program(Plan(PLAN_PATH))
    print(json.dumps(report, indent=2))
    print(f"wrote {OUT_NBT}")
    print(f"wrote {PROGRAM_PATH}")
